language: java

install: echo "I trust Maven."

# don't just run the tests, also run Findbugs and friends
script: mvn verify

after_success: mvn cobertura:cobertura coveralls:cobertura

jdk:
  - oraclejdk7
  - oraclejdk8
